### ISSUE TITLE
Spawner blocks not working after purchase from shop

### ISSUE THREAD

**Issue by Megazac1** [DeveloperRic/CustomShop#10]
*****Posting this here at the request of the developer for tracking***

I'm having an awful time trying to figure out how to designate spawners in my spawn shop to be specific to the mob its supposed to spawn.

Using the given config upon download, and working on this as server admin in permissions....

Error in the ingame console says "Placing default spawner (either this spawner is invalid or disabled).

Error in server console: "ERROR Could not pass event BlockPlaceEvent to CustomShop v2.0.0" (full console output at the bottom)

spawners:
name: '&aSpawners'
permission: 'customshop.spawners'
items:
test: '52:50,1,60000,0,-'
test1: '52:51,1,60000,0,-'
test2: '52:52,1,60000,0,-'
#test3: '52:53,1,60000,0,-, buy:[/broadcast &e<player> just bought an Iron Golem Spawner!]'

After purchasing these spawners in game, once placed, they all come out as Pig spawners, even though their entity IDs are all different. Creeper, Skeleton, Spider, in that order actually. The error above displays once I have placed the spawner. I have Silk Spawners running on my server. I'm still very new to Minecraft server administration, so forgive me if this is "another newb post." Thanks so much in advance for the help. I absolutely love this plugin.

Main plugins and server...
Spigot 1.11.2
Multiverse Core
PermissionsEx
Vault
SaneEconomy
Customer Shop Gui
Silk Spawners

12.05 18:59:40 [Server] ERROR Could not pass event BlockPlaceEvent to CustomShop v2.0.0
12.05 18:59:40 [Server] INFO org.bukkit.event.EventException
12.05 18:59:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:147) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.ItemStack.placeItem(ItemStack.java:193) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:491) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
12.05 18:59:40 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
12.05 18:59:40 [Server] INFO Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.Creeper
12.05 18:59:40 [Server] INFO at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_45]
12.05 18:59:40 [Server] INFO at org.bukkit.entity.EntityType.valueOf(EntityType.java:1) ~[spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
12.05 18:59:40 [Server] INFO at com.rictacius.customShop.Shops.onPlaceSpawner(Shops.java:373) ~[?:?]
12.05 18:59:40 [Server] INFO at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[?:?]
12.05 18:59:40 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
12.05 18:59:40 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
12.05 18:59:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]

**Comment by ghost** [comment]
I get the same issue. WTF... this needs fixed!

**Comment by DeveloperRic** [comment]
I have been very busy with other tasks. I will fix this bug ASAP, sorry for the inconvenience.

**Comment by DeveloperRic** [comment]
Spigot 1.11.2 is causing a lot of trouble with Custom Shop. I'm not entirely sure why, maybe because deprecated methods have been wiped, and cross-compatibility is not possible. I have made the downloads separate for 1.11.2 and can be found on my downloads page [here](http://www.victorolaitan.xyz/ric) or if that doesn't work, then [here](http://www.rictacius.000webhostapp.com/ric)

**Comment by ghost** [comment]
It is not just 1.11.2. I have the error on my Spigot 1.8 factions server.

**Comment by DeveloperRic** [comment]
Well, I am currently fixing some back-end issues. I will continue work on this bug once that issue is resolved.

**Comment by DeveloperRic** [comment]
Very sorry for the insane delay here. It seems Spigot hasn't registered the EntityType "creeper" in its enum. I'm afraid there is nothing I can do to fix this as the spawner section of Custom Shop is known to be unstable and I have ended development on the plugin. I recommend you find someone who can make a version of Custom Shop with a better spawner section or don't use the section entirely. Good luck! 😃
