### ISSUE TITLE
buy/sell Commands

### ISSUE THREAD

**Issue by SirBlobman** [DeveloperRic/CustomShop#15]
Any time I type a command after "buy:[" or "sell:[" it just says the command instead of actually executing it

Config: `buy:[broadcast &e<player> just bought an Iron Golem Spawner!]`

Chat: ![image](https://user-images.githubusercontent.com/9003290/36948234-cbfb1934-1fa5-11e8-8c63-e5c808cf99cc.png)

**Comment by DeveloperRic** [comment]
@SirBlobman please try again with the latest version (unfortunately doesn't support placeholders like `<player>` but the command will be executed by the player not server)

reopen if you still have issues
