### ISSUE TITLE
Using command /shop

### ISSUE THREAD

**Issue by PotPlease** [DeveloperRic/CustomShop#18]
When I try the command /shop the following erros pop up can someone please explain?
INFO PotPlease issued server command: /shop
16.12 01:27:32 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to CustomShop v2.0.2

**Comment by DeveloperRic** [comment]
Hey there, do you mind sending the full error from console?

**Comment by PotPlease** [comment]
> Hey there, do you mind sending the full error from console?

that is the only error code I will put everything that comes after ,but I don't know if they are releated
INFO PotPlease issued server command: /shop
16.12 01:27:32 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to CustomShop v2.0.2
16.12 01:27:32 [Server] INFO org.bukkit.event.EventException
16.12 01:27:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
16.12 01:27:32 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
16.12 01:27:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(Minecraft

**Comment by DeveloperRic** [comment]
It seems that this error is not arising from CustomShop; I cannot find a trace element that points to somewhere within the CustomShop code.

**Comment by PotPlease** [comment]
would you have any idea how to fix this?
