### ISSUE TITLE
Sign not working

### ISSUE THREAD

**Issue by knightofmercs** [DeveloperRic/CustomShop#20]
this is what I have for my sign,

Line1: [CustomShop]
Line2: Buy / Sell
Line3: either blank or name of shop Example Ores.

but the sign is not doing anything when I click on it. 
the shop works if I type /sell or /buy. I am running version 1.11

please help

**Comment by DeveloperRic** [comment]
Hello, Sign Support has been deprecated since the previous release and is not being included in the upcoming release.

Maybe in the future though
