### ISSUE TITLE
/Sell Not Working

### ISSUE THREAD

**Issue by EdwardTheMaster** [DeveloperRic/CustomShop#4]
whenever i tried to /sell put everything there, it gives me nothing, even unsellable item went poof, and also when you tried to /shop and sell item on the item Buy and Sell (Left and Right clicking) theres a problem too, example "i want to sell 24 Sugar canes at 100/16 Canes, but after i have 8 left and sell it. it gives me the $100 although it was 8 Cane

Plugin was good, easy to use but too many bugs.

from console
13.04 06:30:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
13.04 06:30:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
13.04 06:30:12 [Server] INFO at sun.reflect.GeneratedMethodAccessor1006.invoke(Unknown Source) ~[?:?]
13.04 06:30:12 [Server] INFO at com.rictacius.customShop.Sell.onExit(Sell.java:92) ~[?:?]
13.04 06:30:12 [Server] INFO at com.rictacius.customShop.Sell.checkShops(Sell.java:35) ~[?:?]
13.04 06:30:12 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
13.04 06:30:12 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
13.04 06:30:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1619) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:882) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-20170302a.jar:git-Spigot-d4f98a3-cb61ac0]
13.04 06:30:12 [Server] INFO org.bukkit.event.EventException
13.04 06:30:12 [Server] ERROR Could not pass event InventoryCloseEvent to CustomShop v2.0.0

**Comment by DeveloperRic** [comment]
What version of customshop are you using?

**Comment by EdwardTheMaster** [comment]
2.0.0 and Spigot 1.11.2

**Comment by DeveloperRic** [comment]
Spigot 1.11 is known to cause major issues with custom shop. I am trying my best to figure out why and i will notify you once a fix is found. Sorry for the inconvenience 😃

**Comment by DeveloperRic** [comment]
The issues regarding Custom Shop and Spigot 1.11.2, have - fingers crossed - been fixed. You can either download the updated version from [here](https://www.spigotmc.org/resources/custom-shop-gui.28178/), or use (/shop update) ingame and restart your server.
