### ISSUE TITLE
File won't save

### ISSUE THREAD

**Issue by ghost** [DeveloperRic/CustomShop#5]
The shop items don't save for me

**Comment by DeveloperRic** [comment]
You need to provide more information than that for me to help you.

- [ ] What version of custom shop are you using?
- [ ] Send the configuration of your shops.yml and config.yml files.
- [ ] Send any console errors, preferably in text format.
- [ ] If you have any "oldshops.yml" or "oldconfig.yml" files, send them too

**Comment by ghost** [comment]
Basically I create a shop on the server. It works fine, I can buy and sell items and open the shop etc. However, when I stop the server and then start it again, the shop isn't there anymore and isn't saved in the config.

I am using Spigot 1.11.2 and the latest version of the Shop plugin. I can't find any errors either.

I have not changed anything in the config files, I have used it just as it comes.

**Comment by DeveloperRic** [comment]
Spigot 1.11.2 is known to cause major issues with custom shop. I am trying my best to figure out why and i will notify you once a fix is found. Sorry for the inconvenience 😃

**Comment by ghost** [comment]
Okay thanks!

**Comment by DeveloperRic** [comment]
The issues regarding Custom Shop and Spigot 1.11.2, have - fingers crossed - been fixed. You can either download the updated version from [here](https://www.spigotmc.org/resources/custom-shop-gui.28178/), or use (/shop update) ingame and restart your server.
