### ISSUE TITLE
Shop Shift-Click item in an inventory bug

### ISSUE THREAD

**Issue by Aotreborn111** [DeveloperRic/CustomShop#6]
When I open the shop and shift-click my item(s) in an inventory that item(s) will be moved to the shop inventory and will not disappear until I reload the plugin.
----------------------------------------------------------------------------
Server version git-Spigot-625bc00-41a7d14 (MC: 1.11.2)
(Implementing API version 1.11.2-R0.1-SNAPSHOT) & Custom Shop GUI 2.0.0
![image](https://cloud.githubusercontent.com/assets/27740635/25149978/9e13564a-24aa-11e7-8276-6bf9bb2a7a2f.png)

**Comment by DeveloperRic** [comment]
Spigot 1.11.2 is known to cause major issues with custom shop. I am trying my best to figure out why and i will notify you once a fix is found. Sorry for the inconvenience 😃

**Comment by DeveloperRic** [comment]
The issues regarding Custom Shop and Spigot 1.11.2, have - fingers crossed - been fixed. You can either download the updated version from [here](https://www.spigotmc.org/resources/custom-shop-gui.28178/), or use (/shop update) ingame and restart your server.
