### ISSUE TITLE
/shop bug, cant buy and getting unlimited items for free from /shop

### ISSUE THREAD

**Issue by CyclopYT** [DeveloperRic/CustomShop#7]
hello, when player goes to /shop menu (not ops) it is not opening Buy menu where u can buy and sell stuff, it only gives player item for free that they are clicking, can u please help me?

**Comment by DeveloperRic** [comment]
What version of Spigot and custom shop are you using?

**Comment by DeveloperRic** [comment]
Please respond or i will close this issue.
