### ISSUE TITLE
Unable to alias to /shop

### ISSUE THREAD

**Issue by UnknownShadow200** [DeveloperRic/CustomShop#8]
For example, putting this in commands.yml
```
  buy:
  - shop
```
causes /buy to show nothing, no matter what arguments are provided.

I'm not really familiar with how bukkit works, but it seems like it might be something to do with https://github.com/DeveloperRic/CustomShop/blob/master/CustomShop_1.11/src/customShop/Commands.java#L15 - other plugins I looked at derived from CommandExecutor and override onCommand

(might also be why doing /customshop:shop doesn't work either)

**Comment by DeveloperRic** [comment]
Yes it is to do with that. In the next patch for 1.11.2, I will also be including a fix to allow the plugin to be accessed that way. The fix will be available for all versions.

**Comment by UnknownShadow200** [comment]
Cheers! Thanks for the quick response
